language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "node"
  - "iojs-v1.0"
  - "iojs-v1.1"
  - "iojs-v1.2"
  - "iojs-v1.3"
  - "iojs-v1.4"
  - "iojs-v1.5"
  - "iojs"

addons:
  postgresql: "9.3"

before_install:
  - psql -c 'create database bookshelf_deep_changed_plugin;' -U postgres
