language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "lts/*"
  - "node"

addons:
  postgresql: "9.3"

before_install:
  - psql -c 'create database bookshelf_deep_changed_plugin;' -U postgres

script: npm run test:coveralls
